### ISSUE TITLE
Test scripts template 

### ISSUE THREAD

**Issue by Franias** [Franias/ProjetoS2B#14]
To complete the end of the tests for proper documentation.

**Comment by Franias** [comment]
[Test Script.docx](https://github.com/Franias/ProjetoS2B/files/1360399/Test.Script.docx)

**Comment by Franias** [comment]
[Test Script.docx](https://github.com/Franias/ProjetoS2B/files/1388321/Test.Script.docx)

**Comment by Eduarda96** [comment]
[Test.Script.docx](https://github.com/Franias/ProjetoS2B/files/1388678/Test.Script.docx)

Test Script pronto!
