### ISSUE TITLE
Bug: Pesquisa de Solicitações de Documentos Oficiais shouldn't continue without a correct data.

### ISSUE THREAD

**Issue by Franias** [Franias/ProjetoS2B#16]
![acusa o erro](https://user-images.githubusercontent.com/29545628/31242738-57e195ec-a9de-11e7-8f0b-782403cb460f.png)
![dataerradapesquisa](https://user-images.githubusercontent.com/29545628/31242737-57dff9c6-a9de-11e7-882b-2f6ab3229072.png)
![mesmocomoerroelepermiteaconsulta](https://user-images.githubusercontent.com/29545628/31242739-57f88e64-a9de-11e7-853d-01ad0e4282bc.png)

**Comment by Eduarda96** [comment]
![datainvalidafuncionando](https://user-images.githubusercontent.com/14983085/31350662-69a61f28-acfe-11e7-937d-e28cb745b163.jpg)

Quando colocamos data inválida, o programa mostra a mensagem "Data Inválida!" e volta para tela de Pesquisa de Solicitação de Documentos.
