### ISSUE TITLE
Bug: Cadastro de Usuários should not allow invalid CPF 

### ISSUE THREAD

**Issue by Franias** [Franias/ProjetoS2B#17]
![1cpfinvalido](https://user-images.githubusercontent.com/29545628/31246435-c933dc64-a9e3-11e7-82a4-c5678579df16.png)

**Comment by Eduarda96** [comment]
![cpfvalidos](https://user-images.githubusercontent.com/14983085/31350894-3e94de04-acff-11e7-9869-8d1715e9d603.jpg)
Aceita somente CPF válidos.
