### ISSUE TITLE
Bug: Cadastro de Usuários should not complete without all the *required fields completed

### ISSUE THREAD

**Issue by Franias** [Franias/ProjetoS2B#21]
![cadastro passa mesmo nao tendo esses campos obrigatorios preenchidos pelo usuario](https://user-images.githubusercontent.com/29545628/31247365-b72cedaa-a9e6-11e7-9b49-a355cfb2d7c6.png)

**Comment by Eduarda96** [comment]
![camposobrigatorios](https://user-images.githubusercontent.com/14983085/31350955-86f630a8-acff-11e7-99ee-48db18464db7.jpg)
Aceita somente que todos os campos obrigatórios estejam preenchidos.
