### ISSUE TITLE
Bug: Layout(Home) should be with accentuation.

### ISSUE THREAD

**Issue by Eduarda96** [Franias/ProjetoS2B#4]
![erroacentuacao](https://user-images.githubusercontent.com/14983085/30980266-db4c24c0-a456-11e7-8803-11608079c97a.jpg)

**Comment by Franias** [comment]
![4](https://user-images.githubusercontent.com/29545628/31033111-4065fbc2-a535-11e7-8e7d-e87544416377.png)
Corrigido.
