### ISSUE TITLE
Bug: Menu Dropdown (Usuários) should be with accentuation

### ISSUE THREAD

**Issue by Eduarda96** [Franias/ProjetoS2B#5]
![erroacentuacao2](https://user-images.githubusercontent.com/14983085/30980858-d552c400-a458-11e7-80f1-9330a38d1342.jpg)

**Comment by Franias** [comment]
its done
![5](https://user-images.githubusercontent.com/29545628/31033218-9800626e-a535-11e7-965e-caa5649924f1.png)
