### ISSUE TITLE
Bug: Menu Dropdown (Documento Oficiais) should be with accentuation

### ISSUE THREAD

**Issue by Eduarda96** [Franias/ProjetoS2B#6]
![erroacentuacao3](https://user-images.githubusercontent.com/14983085/30981115-b3730858-a459-11e7-9870-57a06de81ac8.jpg)

**Comment by Franias** [comment]
![6](https://user-images.githubusercontent.com/29545628/31033316-ed6f89a0-a535-11e7-9ded-4eecb4445e12.png)
Its done.
