### ISSUE TITLE
Bug: Layout(Pesquisa de Solicitações de Documentos Oficiais) should be with accentuation.

### ISSUE THREAD

**Issue by Eduarda96** [Franias/ProjetoS2B#7]
![erropesquisasolitacao](https://user-images.githubusercontent.com/14983085/31030458-d16a8a20-a52b-11e7-8531-6cf0e2524169.jpg)

**Comment by Franias** [comment]
![5](https://user-images.githubusercontent.com/29545628/31033149-6ae1d100-a535-11e7-96e5-6f34229928e9.png)
Its done.

**Comment by Franias** [comment]
![7](https://user-images.githubusercontent.com/29545628/31033275-c8ea9d04-a535-11e7-989a-49bb330dd18f.png)
