### ISSUE TITLE
Bug: Formulário de solicitação de documentos oficiais should be with a correct data.

### ISSUE THREAD

**Issue by Franias** [Franias/ProjetoS2B#8]
The days of the months aren't correct.

**Comment by Eduarda96** [comment]
![1](https://user-images.githubusercontent.com/14983085/31138230-2594a1ba-a844-11e7-8aa2-8250aabea3d8.jpg)

**Comment by Eduarda96** [comment]
![2](https://user-images.githubusercontent.com/14983085/31138247-2f467d32-a844-11e7-98b4-4c6b05dc60c5.jpg)

**Comment by Franias** [comment]
2017-10-03 14:07 GMT-03:00 Eduarda96 <notifications@github.com>:

**Comment by Franias** [comment]
![8](https://user-images.githubusercontent.com/29545628/31188892-e7ea95f8-a90c-11e7-8070-b82bcabd1b42.png)
